# Generated by Django 4.0.6 on 2022-07-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cleaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cleaning',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateField(verbose_name='Date of Cleaning '),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='parts',
            field=models.ManyToManyField(to='main_app.part'),
        ),
    ]
