# Generated by Django 4.0.6 on 2022-07-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_part_alter_cleaning_options_alter_cleaning_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.keyboard')),
            ],
        ),
    ]
